### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by djmissmills** [halfmage/11tea#1]
Hey, would really like to use this, however Im getting the following when I do the initial build. Any idea? Thank you

lorraines-iMac:11tea lorrainemills$ npm run build

> 11tea@1.0.0 build
> ELEVENTY_PRODUCTION=true eleventy && NODE_ENV=production postcss src/styles/tailwind.css --o dist/style.css && cleancss dist/style.css -o dist/style.css

dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/lorrainemills/Desktop/11tea/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/lorrainemills/Desktop/11tea/node_modules/@11ty/eleventy-img/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/lorrainemills/Desktop/11tea/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/lorrainemills/Desktop/11tea/node_modules/@11ty/eleventy-img/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

sh: line 1:  2519 Abort trap: 6           ELEVENTY_PRODUCTION=true eleventy
lorraines-iMac:11tea lorrainemills$

**Comment by pascalandy** [comment]
I would like to see this project being updated as well. It's such a great stack. Cheers!

**Comment by halfmage** [comment]
Hey @djmissmills and @pascalandy Thanks for your feedback! Didn't know that the project has some fans already!
I will investigate this and keep you updated!

**Comment by halfmage** [comment]
pushed an update. install, build and start commands should work now
- updated dependencies
- removed eleventy-plugin-lazyimages
- fixed image paths

Besides this I am working right now on the new version for this project since it is couple of months old. If you like you can check out the develop branch already.

**Comment by djmissmills** [comment]
Brilliant stuff @halfmage thanks. Look forward to checking it out
